services:
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
  django:
    depends_on:
      - db
    ports:
      - "8000:8000"
    build: ./core
    env_file:
      - .env

  flask:
    depends_on:
      - django
    ports:
      - "5001:5000"
    build: ./ingestion
    env_file:
      - .env

volumes:
  db_data: